{{- if .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nomen.name" . }}
  labels:
    {{- include "nomen.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "nomen.name" . }}
          port: {{ .Values.service.port }}
  {{- with .Values.traefik.ingressRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  tls: {}
  {{- end }}
{{- end }}
