{{- if .Values.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nomen.name" . }}-init
  labels:
    {{- include "nomen.labels" . | nindent 4 }}
  {{- if .Values.init.useHelmHook }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.init.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "nomen.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: {{ include "nomen.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["nomen", "init"]
          env:
            {{- include "nomen.env" . | nindent 12 }}
{{- end }}
